# Generated by Django 6.1.1 on 2026-10-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='title',
            new_name='name',
        ),
    ]
